# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 66b64ee538ed1779a144b439be0eae54e9d140c3209b50d2fa1470fabd0ee1b0541d78c77eafe33fc379eac677e0441e77443cfcd90f690b6b716e64d35b6c74

test:
  secret_key_base: f156eeaf1ab8ca886a4f8fe730c00171b559f4b47b82ba9d59ae6751a3f30707aff43e4ca4bc97a99422af28811ab5b7451422c204b8512aee7da8c667db4b14

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
